name: Validate notebooks

on:
  pull_request:
    paths:
      - "notebooks/**/*.cnb.md"

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      CDM_PAT: ${{ secrets.CDM_PAT }}
    steps:
      - uses: actions/checkout@v4

      - name: Install cdm
        run: curl -fsSL https://cli-dist.codatum.com/install.sh | sh

      - name: Validate
        run: cdm notebook validate notebooks/
